spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/brunch_db_
    #    username: brunch_db
    username: root
    password:
    #    password: 0dj7CCMNZ7nnuA9c
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mail:
    host: smtp.mailtrap.io
    port: 2525
    password: 63ad390c2522b5
    username: 1faf2921b418aa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


