spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/brunch_db
#    username: brunch
    username: root
    password:
#    password: 906ggMHcA5B2d04LdaN
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


  mail:
    host: smtp.mailtrap.io
    port: 2525
    password: 1302e6df55c96f
    username: f97ce35e601962
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  mail:
#    host: mail.isteah.ht
#    port: 465
#    username: info.brunch@isteah.ht
#    password: 63ad390c2522b5
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
#          starttls:
#            enable: true
#          socketFactory:
#            class: javax.net.ssl.SSLSocketFactory
#            fallBack: false
#    default-encoding: UTF-8